# Update this to your own host
# If omitted, the system default will be used
# host = "host.docker.internal"
# Functions to skip building
# excluded_functions = ["hello-world"]

[env]
# Relative to the config.toml
# file_path = ".env"
# Rename/add keys that match the environment variable names
# used in your function
# MY_API_KEY = "key"

[env.production]
# Uncomment the line below to use a different path for your production environment
# file_path = ".env"

project_id = "mpmkbtsufihzdelrlszs"

[process-receipt]
verify_jwt = true

[generate-pdf-report]
verify_jwt = true

[test-gemini]
verify_jwt = false

[public-test-gemini]
verify_jwt = false
# This is a public test function that doesn't require authentication
# It's used to test the Gemini API connection

[simple-test]
verify_jwt = false
# This is a simple test function that doesn't require authentication
# It's used to test if edge functions are working at all

[create-checkout-session]
verify_jwt = true
# Stripe checkout session creation requires authentication

[stripe-webhook]
verify_jwt = false
# Stripe webhook doesn't use JWT auth, it uses webhook signatures
