# Paperless Maverick Deployment Configuration
# Comprehensive configuration for deployment automation
# Version: 1.0.0

# Global deployment settings
global:
  version: "1.0.0"
  project_name: "paperless-maverick"
  default_timeout: 600
  health_check_timeout: 300
  backup_retention_days: 30
  log_retention_days: 90

# Environment configurations
environments:
  production:
    namespace: "paperless-maverick"
    domain: "mataresit.com"
    replicas:
      app: 3
      workers: 3
    resources:
      app:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      workers:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
    feature_flags:
      embedding_monitoring:
        enabled: true
        rollout_percentage: 10
        target_teams: ["internal-testing-team"]
      queue_processing:
        enabled: false
        rollout_percentage: 0
        fallback_enabled: true
      batch_optimization:
        enabled: false
        rollout_percentage: 0
        rate_limiting_enabled: false
    monitoring:
      prometheus_enabled: true
      grafana_enabled: true
      alerting_enabled: true
      metrics_retention: "30d"
    security:
      network_policies_enabled: true
      pod_security_standards: "restricted"
      rbac_enabled: true
    
  staging:
    namespace: "paperless-maverick-staging"
    domain: "staging.mataresit.com"
    replicas:
      app: 2
      workers: 2
    resources:
      app:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "250m"
          memory: "512Mi"
      workers:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
    feature_flags:
      embedding_monitoring:
        enabled: true
        rollout_percentage: 50
      queue_processing:
        enabled: true
        rollout_percentage: 25
        fallback_enabled: true
      batch_optimization:
        enabled: true
        rollout_percentage: 25
        rate_limiting_enabled: true
    monitoring:
      prometheus_enabled: true
      grafana_enabled: true
      alerting_enabled: false
      metrics_retention: "7d"
    security:
      network_policies_enabled: false
      pod_security_standards: "baseline"
      rbac_enabled: true

  development:
    namespace: "paperless-maverick-dev"
    domain: "dev.mataresit.com"
    replicas:
      app: 1
      workers: 1
    resources:
      app:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "256Mi"
      workers:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
    feature_flags:
      embedding_monitoring:
        enabled: true
        rollout_percentage: 100
      queue_processing:
        enabled: true
        rollout_percentage: 100
        fallback_enabled: true
      batch_optimization:
        enabled: true
        rollout_percentage: 100
        rate_limiting_enabled: true
    monitoring:
      prometheus_enabled: false
      grafana_enabled: false
      alerting_enabled: false
      metrics_retention: "1d"
    security:
      network_policies_enabled: false
      pod_security_standards: "privileged"
      rbac_enabled: false

# Deployment phases configuration
deployment_phases:
  prerequisites_check:
    enabled: true
    timeout: 60
    required_tools: ["kubectl", "docker", "node", "npm", "curl", "jq"]
    
  environment_validation:
    enabled: true
    timeout: 120
    validate_manifests: true
    validate_secrets: true
    validate_connectivity: true
    
  backup_creation:
    enabled: true
    timeout: 300
    include_kubernetes_state: true
    include_image_versions: true
    include_feature_flags: true
    include_metadata: true
    
  infrastructure_deployment:
    enabled: true
    timeout: 600
    manifests:
      - "namespace.yaml"
      - "configmap.yaml"
      - "secrets.yaml"
      - "deployment.yaml"
      - "service.yaml"
      - "hpa.yaml"
    worker_manifests:
      - "embedding-worker-configmap.yaml"
      - "embedding-queue-worker-deployment.yaml"
      - "embedding-worker-hpa.yaml"
      - "worker-health-monitoring.yaml"
    
  database_migration:
    enabled: true
    timeout: 900
    validate_before: true
    create_backup: true
    rollback_on_failure: true
    
  application_deployment:
    enabled: true
    timeout: 600
    strategy: "RollingUpdate"
    max_surge: 1
    max_unavailable: 0
    
  feature_flag_deployment:
    enabled: true
    timeout: 300
    restart_deployments: true
    validate_after: true
    
  monitoring_deployment:
    enabled: true
    timeout: 600
    components: ["prometheus", "grafana", "alertmanager"]
    
  deployment_validation:
    enabled: true
    timeout: 300
    health_checks: true
    readiness_checks: true
    performance_checks: false
    
  performance_validation:
    enabled: false
    timeout: 600
    load_test: false
    benchmark: false

# Rollback configuration
rollback:
  enabled: true
  automatic_triggers:
    deployment_failure: true
    health_check_failure: true
    performance_degradation: false
  manual_approval_required: false
  preserve_data: true
  timeout: 300

# Monitoring and alerting
monitoring:
  deployment_metrics: true
  audit_logging: true
  performance_tracking: true
  error_tracking: true
  
  alerts:
    deployment_failure: true
    rollback_triggered: true
    validation_failure: true
    timeout_exceeded: true
    
  notifications:
    slack_enabled: false
    email_enabled: false
    pagerduty_enabled: false

# Security settings
security:
  require_signed_images: false
  scan_images: true
  validate_rbac: true
  check_network_policies: true
  audit_deployment_changes: true

# Feature flag management
feature_flag_management:
  gradual_rollout: true
  canary_deployment: true
  a_b_testing: false
  rollback_on_error: true
  
  rollout_strategy:
    initial_percentage: 5
    increment_percentage: 10
    increment_interval: "1h"
    max_percentage: 100
    
  validation_criteria:
    error_rate_threshold: 0.05
    response_time_threshold: 2000
    success_rate_threshold: 0.95

# Integration settings
integrations:
  github_actions: true
  slack_notifications: false
  datadog_monitoring: false
  sentry_error_tracking: true
  
# Validation rules
validation:
  required_secrets: ["supabase-secrets", "ai-secrets", "security-secrets"]
  required_configmaps: ["paperless-maverick-config", "embedding-worker-config"]
  health_check_endpoints: ["/health", "/ready"]
  performance_thresholds:
    response_time_p95: 2000
    error_rate: 0.05
    cpu_utilization: 0.8
    memory_utilization: 0.8
