# Deployment Monitoring Configuration for Paperless Maverick
# Defines monitoring behavior, metrics collection, and alerting policies
# Version: 1.0.0

# Global monitoring settings
global:
  version: "1.0.0"
  project_name: "paperless-maverick"
  monitoring_interval: 30
  metrics_retention_days: 30
  log_retention_days: 90
  audit_retention_days: 365

# Environment-specific monitoring configurations
environments:
  production:
    monitoring_policy:
      continuous_monitoring: true
      metrics_export_enabled: true
      audit_logging_enabled: true
      error_tracking_enabled: true
      performance_monitoring_enabled: true
      
    collection_intervals:
      metrics_collection: 30  # seconds
      health_checks: 15      # seconds
      performance_checks: 60  # seconds
      audit_events: 10       # seconds
      
    retention_policies:
      metrics_retention: 30   # days
      logs_retention: 90     # days
      audit_retention: 365   # days
      error_logs_retention: 180  # days
      
    alerting_thresholds:
      deployment_availability_critical: 50  # percentage
      deployment_availability_warning: 80   # percentage
      health_score_critical: 50            # percentage
      health_score_warning: 70             # percentage
      response_time_critical: 5000         # milliseconds
      response_time_warning: 2000          # milliseconds
      error_rate_critical: 10              # percentage
      error_rate_warning: 5                # percentage
      
  staging:
    monitoring_policy:
      continuous_monitoring: true
      metrics_export_enabled: true
      audit_logging_enabled: true
      error_tracking_enabled: true
      performance_monitoring_enabled: false
      
    collection_intervals:
      metrics_collection: 60  # seconds
      health_checks: 30      # seconds
      performance_checks: 120 # seconds
      audit_events: 30       # seconds
      
    retention_policies:
      metrics_retention: 14   # days
      logs_retention: 30     # days
      audit_retention: 90    # days
      error_logs_retention: 60  # days
      
    alerting_thresholds:
      deployment_availability_critical: 30  # percentage
      deployment_availability_warning: 60   # percentage
      health_score_critical: 40            # percentage
      health_score_warning: 60             # percentage
      response_time_critical: 8000         # milliseconds
      response_time_warning: 4000          # milliseconds
      error_rate_critical: 20              # percentage
      error_rate_warning: 10               # percentage
      
  development:
    monitoring_policy:
      continuous_monitoring: false
      metrics_export_enabled: false
      audit_logging_enabled: true
      error_tracking_enabled: true
      performance_monitoring_enabled: false
      
    collection_intervals:
      metrics_collection: 120 # seconds
      health_checks: 60      # seconds
      performance_checks: 300 # seconds
      audit_events: 60       # seconds
      
    retention_policies:
      metrics_retention: 7    # days
      logs_retention: 14     # days
      audit_retention: 30    # days
      error_logs_retention: 30  # days
      
    alerting_thresholds:
      deployment_availability_critical: 20  # percentage
      deployment_availability_warning: 40   # percentage
      health_score_critical: 30            # percentage
      health_score_warning: 50             # percentage
      response_time_critical: 10000        # milliseconds
      response_time_warning: 6000          # milliseconds
      error_rate_critical: 30              # percentage
      error_rate_warning: 20               # percentage

# Metrics collection configuration
metrics_collection:
  kubernetes_metrics:
    enabled: true
    collect_deployments: true
    collect_pods: true
    collect_services: true
    collect_configmaps: true
    collect_secrets: false  # Security: don't collect secret data
    collect_events: true
    
  health_metrics:
    enabled: true
    health_endpoints:
      - "/health"
      - "/ready"
      - "/api/monitoring/health"
    response_time_tracking: true
    endpoint_availability_tracking: true
    
  performance_metrics:
    enabled: true
    cpu_usage_tracking: true
    memory_usage_tracking: true
    disk_usage_tracking: false
    network_io_tracking: false
    
  resource_metrics:
    enabled: true
    node_metrics: true
    cluster_metrics: true
    namespace_metrics: true
    
  custom_metrics:
    enabled: true
    deployment_lifecycle_events: true
    error_pattern_analysis: true
    audit_event_tracking: true

# Prometheus integration
prometheus:
  enabled: true
  push_gateway:
    url: "http://prometheus-pushgateway:9091"
    job_name: "deployment-monitoring"
    push_interval: 30  # seconds
    
  recording_rules:
    enabled: true
    rules_file: "prometheus/rules/deployment-monitoring-rules.yml"
    
  alerting_rules:
    enabled: true
    alert_groups:
      - deployment_availability
      - deployment_health
      - deployment_performance
      - cluster_health
      
  metrics_export:
    deployment_metrics: true
    health_metrics: true
    performance_metrics: true
    resource_metrics: true
    lifecycle_metrics: true

# Logging configuration
logging:
  log_levels:
    deployment_log: "INFO"
    metrics_log: "DEBUG"
    audit_log: "INFO"
    error_log: "ERROR"
    
  log_formats:
    timestamp_format: "%Y-%m-%d %H:%M:%S"
    include_session_id: true
    include_environment: true
    include_namespace: true
    
  log_rotation:
    enabled: true
    max_file_size: "100MB"
    max_files: 10
    compress_old_logs: true
    
  structured_logging:
    enabled: true
    format: "json"
    include_metadata: true

# Audit trail configuration
audit_trail:
  enabled: true
  audit_events:
    deployment_lifecycle: true
    configuration_changes: true
    user_actions: true
    system_events: true
    error_events: true
    
  audit_metadata:
    include_user_info: true
    include_session_info: true
    include_environment_info: true
    include_timestamp: true
    
  audit_storage:
    local_storage: true
    remote_storage: false
    encryption_enabled: false
    compression_enabled: true

# Error tracking configuration
error_tracking:
  enabled: true
  error_categories:
    deployment_errors: true
    health_check_errors: true
    performance_errors: true
    configuration_errors: true
    network_errors: true
    
  error_analysis:
    pattern_detection: true
    trend_analysis: true
    correlation_analysis: false
    
  error_reporting:
    immediate_alerts: true
    periodic_summaries: true
    error_dashboards: true

# Alerting configuration
alerting:
  enabled: true
  alert_channels:
    prometheus_alerts: true
    log_based_alerts: true
    metrics_based_alerts: true
    
  notification_channels:
    slack:
      enabled: false
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#deployments"
      
    email:
      enabled: false
      smtp_server: "localhost:587"
      from_address: "monitoring@paperless-maverick.com"
      to_addresses: ["team@paperless-maverick.com"]
      
    pagerduty:
      enabled: false
      integration_key: "${PAGERDUTY_INTEGRATION_KEY}"
      
  alert_rules:
    deployment_down:
      severity: "critical"
      threshold: "deployment_availability < 50%"
      duration: "2m"
      
    deployment_degraded:
      severity: "warning"
      threshold: "deployment_health_score < 70"
      duration: "5m"
      
    high_response_time:
      severity: "warning"
      threshold: "response_time_p95 > 5000ms"
      duration: "3m"
      
    high_error_rate:
      severity: "warning"
      threshold: "error_rate > 10%"
      duration: "2m"

# Dashboard configuration
dashboards:
  enabled: true
  dashboard_types:
    deployment_overview: true
    health_monitoring: true
    performance_monitoring: true
    error_tracking: true
    audit_trail: true
    
  grafana_integration:
    enabled: true
    dashboard_provisioning: true
    auto_import: true
    
  custom_dashboards:
    deployment_lifecycle: true
    resource_utilization: true
    alert_summary: true

# Integration configuration
integrations:
  kubernetes:
    api_version: "v1"
    cluster_monitoring: true
    namespace_isolation: true
    rbac_enabled: true
    
  prometheus:
    scrape_configs: true
    recording_rules: true
    alerting_rules: true
    
  grafana:
    dashboard_import: true
    alert_notifications: true
    
  ci_cd:
    github_actions: true
    deployment_tracking: true
    pipeline_integration: true

# Security configuration
security:
  access_control:
    rbac_enabled: true
    user_authentication: true
    api_key_authentication: false
    
  data_protection:
    log_encryption: false
    metrics_encryption: false
    audit_encryption: true
    
  network_security:
    tls_enabled: true
    certificate_validation: true
    secure_communications: true

# Performance optimization
performance:
  monitoring_optimization:
    batch_metrics_collection: true
    async_processing: true
    connection_pooling: true
    
  resource_limits:
    max_memory_usage: "512Mi"
    max_cpu_usage: "500m"
    max_disk_usage: "1Gi"
    
  caching:
    metrics_caching: true
    cache_ttl: 300  # seconds
    cache_size_limit: "100Mi"

# Feature flags
feature_flags:
  advanced_metrics: true
  real_time_monitoring: true
  predictive_analytics: false
  anomaly_detection: false
  
  rollout_percentages:
    advanced_metrics: 100
    real_time_monitoring: 75
    predictive_analytics: 25
    anomaly_detection: 10

# Maintenance configuration
maintenance:
  automated_cleanup: true
  cleanup_schedule: "0 2 * * *"  # Daily at 2 AM
  
  health_checks:
    monitoring_system_health: true
    storage_health: true
    integration_health: true
    
  backup_and_recovery:
    metrics_backup: false
    logs_backup: true
    audit_backup: true
    backup_retention: 90  # days
