# Rollback Automation Configuration
# Defines rollback policies, triggers, and safety settings
# Version: 1.0.0

# Global rollback settings
global:
  version: "1.0.0"
  project_name: "paperless-maverick"
  default_timeout: 600
  validation_timeout: 300
  backup_retention_days: 30
  max_rollback_attempts: 3

# Environment-specific rollback policies
environments:
  production:
    rollback_policy:
      automated_rollback_enabled: true
      confirmation_required: true
      force_flag_required: true
      reason_required: true
      backup_required: true
      validation_required: true
    
    safety_checks:
      deployment_health_check: true
      database_consistency_check: true
      monitoring_validation: true
      performance_validation: true
      
    approval_workflow:
      single_approval_required: true
      emergency_bypass_allowed: false
      approval_timeout: 300
      
    notification_channels:
      - slack
      - email
      - pagerduty
      
  staging:
    rollback_policy:
      automated_rollback_enabled: true
      confirmation_required: false
      force_flag_required: false
      reason_required: false
      backup_required: true
      validation_required: true
    
    safety_checks:
      deployment_health_check: true
      database_consistency_check: true
      monitoring_validation: false
      performance_validation: false
      
    approval_workflow:
      single_approval_required: false
      emergency_bypass_allowed: true
      approval_timeout: 60
      
    notification_channels:
      - slack
      
  development:
    rollback_policy:
      automated_rollback_enabled: false
      confirmation_required: false
      force_flag_required: false
      reason_required: false
      backup_required: false
      validation_required: false
    
    safety_checks:
      deployment_health_check: false
      database_consistency_check: false
      monitoring_validation: false
      performance_validation: false
      
    approval_workflow:
      single_approval_required: false
      emergency_bypass_allowed: true
      approval_timeout: 30
      
    notification_channels: []

# Rollback trigger configurations
triggers:
  embedding_success_rate:
    enabled: true
    threshold: 85
    window_duration: 600  # 10 minutes
    evaluation_interval: 60
    severity: "high"
    automated_action: "rollback_application"
    
  system_error_rate:
    enabled: true
    threshold: 10
    window_duration: 300  # 5 minutes
    evaluation_interval: 60
    severity: "critical"
    automated_action: "rollback_full"
    
  queue_backlog:
    enabled: true
    threshold: 500
    window_duration: 900  # 15 minutes
    evaluation_interval: 120
    severity: "medium"
    automated_action: "rollback_application"
    
  api_quota_exhaustion:
    enabled: true
    threshold: 95
    window_duration: 120  # 2 minutes
    evaluation_interval: 30
    severity: "high"
    automated_action: "rollback_application"
    
  health_check_failure:
    enabled: true
    threshold: 50
    window_duration: 180  # 3 minutes
    evaluation_interval: 30
    severity: "critical"
    automated_action: "rollback_full"
    
  deployment_failure:
    enabled: true
    threshold: 1
    window_duration: 60   # 1 minute
    evaluation_interval: 15
    severity: "critical"
    automated_action: "rollback_application"

# Rollback component configurations
components:
  application:
    rollback_method: "kubernetes_rollout"
    validation_required: true
    health_check_endpoints:
      - "/health"
      - "/ready"
    rollback_timeout: 300
    
  database:
    rollback_method: "migration_script"
    validation_required: true
    backup_required: true
    rollback_timeout: 600
    consistency_check: true
    
  infrastructure:
    rollback_method: "manifest_restore"
    validation_required: true
    backup_required: true
    rollback_timeout: 300
    
  monitoring:
    rollback_method: "kubernetes_rollout"
    validation_required: false
    rollback_timeout: 180

# Backup configurations
backup:
  pre_rollback_backup:
    enabled: true
    include_secrets: false  # Security: exclude secret data
    include_persistent_volumes: false
    compression: true
    
  backup_storage:
    local_path: "/backups/rollback"
    retention_policy:
      daily_backups: 7
      weekly_backups: 4
      monthly_backups: 12
    
  backup_validation:
    verify_integrity: true
    test_restore: false  # Only for critical backups

# Validation configurations
validation:
  post_rollback_checks:
    deployment_health: true
    endpoint_accessibility: true
    database_connectivity: true
    monitoring_functionality: false
    performance_baseline: false
    
  validation_timeouts:
    health_check: 60
    endpoint_check: 30
    database_check: 120
    monitoring_check: 60
    
  failure_handling:
    retry_attempts: 3
    retry_interval: 30
    escalation_on_failure: true

# Notification configurations
notifications:
  rollback_initiated:
    severity: "high"
    channels: ["slack", "email"]
    template: "rollback_initiated"
    
  rollback_completed:
    severity: "medium"
    channels: ["slack"]
    template: "rollback_completed"
    
  rollback_failed:
    severity: "critical"
    channels: ["slack", "email", "pagerduty"]
    template: "rollback_failed"
    
  automated_trigger_detected:
    severity: "high"
    channels: ["slack", "email"]
    template: "automated_trigger"

# Integration configurations
integrations:
  kubernetes:
    api_version: "apps/v1"
    rollout_strategy: "undo"
    revision_history_limit: 10
    
  database:
    migration_tool: "custom_script"
    backup_tool: "pg_dump"
    validation_queries: true
    
  monitoring:
    prometheus_integration: true
    grafana_integration: true
    custom_metrics: true
    
  ci_cd:
    github_actions: true
    deployment_tracking: true
    rollback_reporting: true

# Security configurations
security:
  audit_logging:
    enabled: true
    log_level: "detailed"
    include_user_actions: true
    retention_days: 90
    
  access_control:
    rbac_enabled: true
    role_based_rollback: true
    emergency_access: true
    
  encryption:
    backup_encryption: true
    log_encryption: false
    transit_encryption: true

# Feature flags
feature_flags:
  automated_rollback: true
  partial_rollback: true
  backup_validation: true
  performance_validation: false
  
  rollout_percentages:
    automated_triggers: 100
    partial_rollback: 75
    advanced_validation: 50

# Monitoring and alerting
monitoring:
  rollback_metrics:
    - rollback_frequency
    - rollback_success_rate
    - rollback_duration
    - trigger_accuracy
    - validation_success_rate
    
  dashboards:
    rollback_overview: true
    trigger_analysis: true
    component_health: true
    
  alerts:
    frequent_rollbacks:
      threshold: 5
      window: "24h"
      severity: "warning"
      
    rollback_failures:
      threshold: 1
      window: "1h"
      severity: "critical"
      
    trigger_false_positives:
      threshold: 3
      window: "6h"
      severity: "medium"

# Testing configurations
testing:
  rollback_testing:
    enabled: true
    test_frequency: "weekly"
    test_environments: ["staging"]
    
  chaos_engineering:
    enabled: false
    failure_injection: false
    recovery_testing: true
    
  validation_testing:
    unit_tests: true
    integration_tests: true
    end_to_end_tests: false
