# Security and Compliance Configuration
# Comprehensive security scanning and compliance validation settings for Paperless Maverick

# Global security settings
security:
  # Vulnerability scanning configuration
  vulnerability_scanning:
    enabled: true
    tools:
      trivy:
        enabled: true
        severity_levels: ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
        fail_on_critical: true
        fail_on_high: false
        timeout: 300
        cache_enabled: true
        
      grype:
        enabled: true
        severity_threshold: "high"
        fail_on_critical: true
        output_format: "json"
        
      snyk:
        enabled: true
        severity_threshold: "high"
        monitor_dependencies: true
        fail_on_issues: true
        
    # Scan targets
    targets:
      containers: true
      dependencies: true
      infrastructure: true
      source_code: true
      
  # Container security settings
  container_security:
    # Image scanning
    image_scanning:
      enabled: true
      scan_on_build: true
      scan_on_deploy: true
      registry_scanning: true
      
    # Runtime security
    runtime_security:
      enabled: true
      monitor_file_integrity: true
      monitor_network_activity: true
      monitor_process_activity: true
      
    # Security policies
    policies:
      disallow_privileged: true
      disallow_root_user: true
      require_read_only_filesystem: true
      require_non_root_user: true
      drop_all_capabilities: true
      
  # Network security
  network_security:
    # Network policies
    network_policies:
      enabled: true
      default_deny_all: true
      allow_dns: true
      allow_monitoring: true
      
    # TLS configuration
    tls:
      min_version: "1.2"
      cipher_suites: ["TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"]
      require_tls: true
      
  # Secrets management
  secrets_management:
    # Encryption
    encryption:
      enabled: true
      algorithm: "AES-256-GCM"
      key_rotation_days: 90
      
    # Secret scanning
    secret_scanning:
      enabled: true
      tools: ["trufflehog", "gitleaks"]
      scan_commits: true
      scan_containers: true
      
    # Access control
    access_control:
      rbac_enabled: true
      service_account_tokens: false
      least_privilege: true

# Compliance frameworks configuration
compliance:
  # SOC 2 Type II compliance
  soc2:
    enabled: true
    controls:
      # Security controls
      security:
        access_controls: true
        authentication: true
        authorization: true
        encryption_at_rest: true
        encryption_in_transit: true
        vulnerability_management: true
        incident_response: true
        
      # Availability controls
      availability:
        monitoring: true
        backup_recovery: true
        capacity_planning: true
        system_availability: true
        
      # Processing_integrity controls
      processing_integrity:
        data_validation: true
        error_handling: true
        data_processing_controls: true
        
      # Confidentiality controls
      confidentiality:
        data_classification: true
        access_restrictions: true
        data_retention: true
        
      # Privacy controls
      privacy:
        data_collection: true
        data_usage: true
        data_retention: true
        data_disposal: true
        
  # GDPR compliance
  gdpr:
    enabled: true
    requirements:
      # Data protection principles
      data_protection:
        lawfulness: true
        fairness: true
        transparency: true
        purpose_limitation: true
        data_minimization: true
        accuracy: true
        storage_limitation: true
        integrity_confidentiality: true
        accountability: true
        
      # Individual rights
      individual_rights:
        right_to_information: true
        right_of_access: true
        right_to_rectification: true
        right_to_erasure: true
        right_to_restrict_processing: true
        right_to_data_portability: true
        right_to_object: true
        rights_automated_decision_making: true
        
      # Technical measures
      technical_measures:
        privacy_by_design: true
        privacy_by_default: true
        data_protection_impact_assessment: true
        data_breach_notification: true
        
  # ISO 27001 compliance
  iso27001:
    enabled: true
    controls:
      # Information security policies
      policies:
        information_security_policy: true
        risk_management: true
        
      # Organization of information security
      organization:
        internal_organization: true
        mobile_devices: true
        teleworking: true
        
      # Human resource security
      human_resources:
        prior_to_employment: true
        during_employment: true
        termination_change_employment: true
        
      # Asset management
      asset_management:
        responsibility_for_assets: true
        information_classification: true
        media_handling: true
        
      # Access control
      access_control:
        business_requirements: true
        user_access_management: true
        user_responsibilities: true
        system_application_access_control: true
        
      # Cryptography
      cryptography:
        cryptographic_controls: true
        key_management: true
        
  # PCI DSS compliance (if applicable)
  pci_dss:
    enabled: false
    requirements:
      # Build and maintain secure network
      network_security:
        firewall_configuration: true
        default_passwords: true
        
      # Protect cardholder data
      data_protection:
        stored_data_protection: true
        transmitted_data_encryption: true
        
      # Maintain vulnerability management
      vulnerability_management:
        antivirus_software: true
        secure_systems_applications: true
        
      # Implement strong access control
      access_control:
        access_control_systems: true
        unique_user_ids: true
        restrict_physical_access: true
        
      # Regularly monitor and test networks
      monitoring:
        access_monitoring: true
        security_testing: true
        
      # Maintain information security policy
      policy:
        security_policy: true

# Audit and reporting configuration
audit:
  # Audit logging
  logging:
    enabled: true
    retention_days: 365
    log_levels: ["INFO", "WARNING", "ERROR", "CRITICAL"]
    
    # Log sources
    sources:
      application_logs: true
      system_logs: true
      security_logs: true
      audit_logs: true
      
  # Compliance reporting
  reporting:
    enabled: true
    formats: ["json", "html", "pdf"]
    frequency: "daily"
    
    # Report types
    types:
      vulnerability_report: true
      compliance_report: true
      security_posture_report: true
      audit_report: true
      
  # Alerting
  alerting:
    enabled: true
    channels: ["email", "slack", "webhook"]
    
    # Alert conditions
    conditions:
      critical_vulnerabilities: true
      compliance_violations: true
      security_incidents: true
      policy_violations: true

# Scanning schedules
schedules:
  # Vulnerability scanning
  vulnerability_scan:
    frequency: "daily"
    time: "02:00"
    timezone: "UTC"
    
  # Compliance validation
  compliance_validation:
    frequency: "weekly"
    day: "sunday"
    time: "03:00"
    timezone: "UTC"
    
  # Security audit
  security_audit:
    frequency: "monthly"
    day: 1
    time: "04:00"
    timezone: "UTC"

# Integration settings
integrations:
  # Security tools
  security_tools:
    # SIEM integration
    siem:
      enabled: false
      endpoint: ""
      api_key: ""
      
    # Vulnerability management
    vulnerability_management:
      enabled: false
      platform: ""
      api_key: ""
      
  # Notification channels
  notifications:
    # Slack integration
    slack:
      enabled: false
      webhook_url: ""
      channel: "#security-alerts"
      
    # Email notifications
    email:
      enabled: true
      smtp_server: ""
      recipients: ["security@mataresit.com"]
      
    # Webhook notifications
    webhook:
      enabled: true
      endpoints: []

# Environment-specific overrides
environments:
  development:
    security:
      vulnerability_scanning:
        fail_on_critical: false
        fail_on_high: false
    compliance:
      soc2:
        enabled: false
      gdpr:
        enabled: false
      iso27001:
        enabled: false
        
  staging:
    security:
      vulnerability_scanning:
        fail_on_critical: true
        fail_on_high: false
    compliance:
      soc2:
        enabled: true
      gdpr:
        enabled: true
      iso27001:
        enabled: true
        
  production:
    security:
      vulnerability_scanning:
        fail_on_critical: true
        fail_on_high: true
    compliance:
      soc2:
        enabled: true
      gdpr:
        enabled: true
      iso27001:
        enabled: true
