# Deployment Validation Framework Configuration
# Defines validation criteria, thresholds, and test configurations
# Version: 1.0.0

# Global validation settings
global:
  version: "1.0.0"
  project_name: "paperless-maverick"
  default_timeout: 1800
  health_check_timeout: 300
  performance_test_duration: 300
  report_retention_days: 30

# Environment-specific validation configurations
environments:
  production:
    validation_policy:
      health_validation_required: true
      performance_validation_required: true
      functional_validation_required: true
      security_validation_required: true
      fail_fast_enabled: false
      parallel_execution_enabled: false
      
    success_criteria:
      health_check_success_rate: 95
      api_response_time_p95: 2000
      api_success_rate: 99
      database_query_time_p95: 500
      embedding_success_rate: 90
      worker_availability: 80
      memory_utilization_max: 85
      cpu_utilization_max: 80
      error_rate_max: 5
      
    thresholds:
      critical_failure_threshold: 1
      warning_threshold: 3
      performance_degradation_threshold: 20
      
  staging:
    validation_policy:
      health_validation_required: true
      performance_validation_required: true
      functional_validation_required: true
      security_validation_required: false
      fail_fast_enabled: false
      parallel_execution_enabled: true
      
    success_criteria:
      health_check_success_rate: 90
      api_response_time_p95: 3000
      api_success_rate: 95
      database_query_time_p95: 1000
      embedding_success_rate: 85
      worker_availability: 70
      memory_utilization_max: 90
      cpu_utilization_max: 85
      error_rate_max: 10
      
    thresholds:
      critical_failure_threshold: 2
      warning_threshold: 5
      performance_degradation_threshold: 30
      
  development:
    validation_policy:
      health_validation_required: true
      performance_validation_required: false
      functional_validation_required: false
      security_validation_required: false
      fail_fast_enabled: true
      parallel_execution_enabled: true
      
    success_criteria:
      health_check_success_rate: 80
      api_response_time_p95: 5000
      api_success_rate: 90
      database_query_time_p95: 2000
      embedding_success_rate: 75
      worker_availability: 60
      memory_utilization_max: 95
      cpu_utilization_max: 90
      error_rate_max: 20
      
    thresholds:
      critical_failure_threshold: 5
      warning_threshold: 10
      performance_degradation_threshold: 50

# Test suite configurations
test_suites:
  health:
    description: "Health and readiness validation"
    timeout: 300
    retry_attempts: 3
    retry_interval: 10
    tests:
      - deployment_health
      - pod_health
      - service_connectivity
      - health_endpoints
      - database_connectivity
      
  performance:
    description: "Performance and load testing"
    timeout: 600
    retry_attempts: 1
    retry_interval: 30
    tests:
      - api_response_time
      - throughput_testing
      - resource_utilization
      - database_performance
      
  functional:
    description: "Functional and integration testing"
    timeout: 900
    retry_attempts: 2
    retry_interval: 15
    tests:
      - api_endpoints
      - embedding_functionality
      - worker_functionality
      - integration_tests
      
  security:
    description: "Security and compliance validation"
    timeout: 600
    retry_attempts: 1
    retry_interval: 0
    tests:
      - security_headers
      - authentication_validation
      - authorization_validation
      - data_encryption_validation

# Test configurations
test_configurations:
  api_response_time:
    test_count: 10
    concurrent_requests: 1
    endpoints:
      - "/health"
      - "/ready"
      - "/api/monitoring/health"
    expected_status_codes: [200]
    
  throughput_testing:
    test_duration: 30
    concurrent_requests: 5
    ramp_up_time: 5
    target_rps: 10
    max_error_rate: 10
    
  resource_utilization:
    monitoring_duration: 60
    check_interval: 10
    cpu_threshold: 80
    memory_threshold: 85
    disk_threshold: 90
    
  database_performance:
    query_timeout: 5
    connection_timeout: 10
    max_connections: 100
    query_types:
      - "SELECT 1"
      - "SELECT COUNT(*) FROM documents"
      
  health_endpoints:
    endpoints:
      - path: "/health"
        expected_status: 200
        timeout: 5
      - path: "/ready"
        expected_status: 200
        timeout: 5
      - path: "/api/monitoring/health"
        expected_status: 200
        timeout: 10

# Validation metrics
metrics:
  collection_enabled: true
  retention_period: "30d"
  export_formats: ["json", "prometheus"]
  
  health_metrics:
    - deployment_ready_replicas
    - pod_health_rate
    - endpoint_availability
    - database_connection_status
    
  performance_metrics:
    - api_response_time_avg
    - api_response_time_p95
    - api_response_time_p99
    - throughput_rps
    - error_rate_percentage
    - cpu_utilization_max
    - memory_utilization_max
    
  functional_metrics:
    - api_endpoint_success_rate
    - embedding_success_rate
    - worker_availability
    - integration_test_success_rate

# Reporting configuration
reporting:
  enabled: true
  formats: ["json", "html", "junit"]
  
  json_report:
    enabled: true
    include_metrics: true
    include_logs: false
    
  html_report:
    enabled: true
    include_charts: true
    include_details: true
    template: "default"
    
  junit_report:
    enabled: false
    test_suite_name: "deployment-validation"
    
  notification:
    enabled: true
    channels: ["slack", "email"]
    on_failure: true
    on_success: false
    on_warning: true

# Integration configurations
integrations:
  prometheus:
    enabled: true
    push_gateway_url: "http://prometheus-pushgateway:9091"
    job_name: "deployment-validation"
    
  grafana:
    enabled: true
    dashboard_id: "deployment-validation"
    
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#deployments"
    
  email:
    enabled: false
    smtp_server: "localhost:587"
    from_address: "deployments@paperless-maverick.com"
    to_addresses: ["team@paperless-maverick.com"]

# Feature flags
feature_flags:
  parallel_execution: true
  advanced_metrics: true
  security_validation: false
  ui_validation: false
  
  rollout_percentages:
    parallel_execution: 75
    advanced_metrics: 50
    security_validation: 25

# Validation rules
validation_rules:
  mandatory_tests:
    production: ["health", "performance", "functional"]
    staging: ["health", "performance"]
    development: ["health"]
    
  optional_tests:
    production: ["security"]
    staging: ["functional", "security"]
    development: ["performance", "functional"]
    
  test_dependencies:
    performance: ["health"]
    functional: ["health"]
    security: ["health", "functional"]

# Error handling
error_handling:
  retry_policy:
    max_attempts: 3
    backoff_strategy: "exponential"
    initial_delay: 5
    max_delay: 60
    
  failure_handling:
    continue_on_warning: true
    continue_on_non_critical: true
    escalate_on_critical: true
    
  timeout_handling:
    default_timeout: 300
    test_specific_timeouts: true
    timeout_escalation: true

# Monitoring and alerting
monitoring:
  validation_metrics:
    - validation_duration
    - test_success_rate
    - failure_frequency
    - performance_trends
    
  alerts:
    validation_failure:
      threshold: 1
      severity: "critical"
      channels: ["slack", "email"]
      
    performance_degradation:
      threshold: 20
      severity: "warning"
      channels: ["slack"]
      
    high_failure_rate:
      threshold: 10
      window: "1h"
      severity: "high"
      channels: ["slack", "email"]
