apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-maverick-config
  namespace: paperless-maverick
  labels:
    app: paperless-maverick
    environment: production
data:
  # Application Configuration
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "3000"
  
  # Feature Flags
  ENABLE_PERFORMANCE_MONITORING: "true"
  ENABLE_SECURITY_LOGGING: "true"
  ENABLE_EMBEDDING_MONITORING: "true"
  ENABLE_QUEUE_PROCESSING: "false"
  ENABLE_BATCH_OPTIMIZATION: "false"
  
  # Rate Limiting Configuration
  API_RATE_LIMIT_WINDOW: "3600"
  API_RATE_LIMIT_MAX_REQUESTS: "1000"
  
  # Cache Configuration
  CACHE_TTL_SECONDS: "300"
  CACHE_MAX_SIZE: "1000"
  
  # Queue Configuration
  QUEUE_POLL_INTERVAL: "5000"
  MAX_CONCURRENT_JOBS: "3"
  QUEUE_RETRY_ATTEMPTS: "3"
  QUEUE_RETRY_DELAY: "5000"
  
  # Monitoring Configuration
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "8080"
  
  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "https://mataresit.com,https://app.mataresit.com"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "X-API-Key,Content-Type,Authorization"
  
  # Rollout Configuration
  EMBEDDING_MONITORING_ROLLOUT_PERCENTAGE: "10"
  QUEUE_PROCESSING_ROLLOUT_PERCENTAGE: "0"
  BATCH_OPTIMIZATION_ROLLOUT_PERCENTAGE: "0"
  
  # Worker Configuration
  MIN_WORKERS: "2"
  MAX_WORKERS: "6"
  WORKER_SCALE_UP_THRESHOLD: "80"
  WORKER_SCALE_DOWN_THRESHOLD: "20"
  
  # Database Configuration
  DB_POOL_SIZE: "10"
  DB_CONNECTION_TIMEOUT: "30000"
  DB_IDLE_TIMEOUT: "600000"
  
  # API Configuration
  API_VERSION: "v1"
  API_TIMEOUT: "30000"
  
  # Backup Configuration
  BACKUP_RETENTION_DAYS: "30"
  BACKUP_SCHEDULE: "0 2 * * *"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: embedding-worker-config
  namespace: paperless-maverick
  labels:
    app: embedding-worker
    environment: production
data:
  # Worker Configuration
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  WORKER_TYPE: "embedding-queue"
  HEALTH_CHECK_PORT: "8080"
  
  # Queue Configuration
  QUEUE_POLL_INTERVAL: "5000"
  MAX_CONCURRENT_JOBS: "3"
  QUEUE_RETRY_ATTEMPTS: "3"
  QUEUE_RETRY_DELAY: "5000"
  BATCH_SIZE: "10"
  
  # Rate Limiting
  MAX_REQUESTS_PER_MINUTE: "60"
  MAX_TOKENS_PER_MINUTE: "100000"
  BACKOFF_MULTIPLIER: "1.5"
  MAX_BACKOFF_MS: "30000"
  
  # Monitoring
  METRICS_ENABLED: "true"
  METRICS_PORT: "9091"
  
  # Performance
  MEMORY_LIMIT: "512Mi"
  CPU_LIMIT: "500m"
