apiVersion: v1
kind: Namespace
metadata:
  name: paperless-maverick
  labels:
    name: paperless-maverick
    environment: production
    app: paperless-maverick
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: paperless-maverick-quota
  namespace: paperless-maverick
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: paperless-maverick-limits
  namespace: paperless-maverick
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
