apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: paperless-maverick
  labels:
    app: paperless-maverick
    environment: production
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # Use: echo -n "your_secret_here" | base64
  url: <BASE64_ENCODED_SUPABASE_URL>
  anon-key: <BASE64_ENCODED_SUPABASE_ANON_KEY>
  service-role-key: <BASE64_ENCODED_SUPABASE_SERVICE_ROLE_KEY>
  
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: paperless-maverick
  labels:
    app: paperless-maverick
    environment: production
type: Opaque
data:
  # Base64 encoded AI API keys
  gemini-api-key: <BASE64_ENCODED_GEMINI_API_KEY>
  openai-api-key: <BASE64_ENCODED_OPENAI_API_KEY>
  
---
apiVersion: v1
kind: Secret
metadata:
  name: security-secrets
  namespace: paperless-maverick
  labels:
    app: paperless-maverick
    environment: production
type: Opaque
data:
  # Base64 encoded security keys
  api-key-encryption-key: <BASE64_ENCODED_API_KEY_ENCRYPTION_KEY>
  jwt-secret: <BASE64_ENCODED_JWT_SECRET>
  
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: paperless-maverick
  labels:
    app: paperless-maverick
    environment: production
type: Opaque
data:
  # Base64 encoded monitoring secrets
  sentry-dsn: <BASE64_ENCODED_SENTRY_DSN>
  grafana-admin-password: <BASE64_ENCODED_GRAFANA_ADMIN_PASSWORD>
  
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: paperless-maverick
  labels:
    app: paperless-maverick
    environment: production
type: Opaque
data:
  # Base64 encoded notification service keys
  resend-api-key: <BASE64_ENCODED_RESEND_API_KEY>
  slack-webhook-url: <BASE64_ENCODED_SLACK_WEBHOOK_URL>
  pagerduty-integration-key: <BASE64_ENCODED_PAGERDUTY_INTEGRATION_KEY>

---
# Template for creating secrets from environment variables
# Run this script to create secrets from your environment:
# 
# kubectl create secret generic supabase-secrets \
#   --from-literal=url="$SUPABASE_URL" \
#   --from-literal=anon-key="$SUPABASE_ANON_KEY" \
#   --from-literal=service-role-key="$SUPABASE_SERVICE_ROLE_KEY" \
#   --namespace=paperless-maverick
#
# kubectl create secret generic ai-secrets \
#   --from-literal=gemini-api-key="$GEMINI_API_KEY" \
#   --from-literal=openai-api-key="$OPENAI_API_KEY" \
#   --namespace=paperless-maverick
#
# kubectl create secret generic security-secrets \
#   --from-literal=api-key-encryption-key="$API_KEY_ENCRYPTION_KEY" \
#   --from-literal=jwt-secret="$JWT_SECRET" \
#   --namespace=paperless-maverick
