apiVersion: v1
kind: Service
metadata:
  name: paperless-maverick-service
  namespace: paperless-maverick
  labels:
    app: paperless-maverick
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: paperless-maverick

---
apiVersion: v1
kind: Service
metadata:
  name: embedding-worker-service
  namespace: paperless-maverick
  labels:
    app: embedding-queue-worker
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: health
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: metrics
  selector:
    app: embedding-queue-worker

---
apiVersion: v1
kind: Service
metadata:
  name: paperless-maverick-loadbalancer
  namespace: paperless-maverick
  labels:
    app: paperless-maverick
    environment: production
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 3000
    protocol: TCP
    name: https
  selector:
    app: paperless-maverick
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-maverick-ingress
  namespace: paperless-maverick
  labels:
    app: paperless-maverick
    environment: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - mataresit.com
    - app.mataresit.com
    - api.mataresit.com
    secretName: paperless-maverick-tls
  rules:
  - host: mataresit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paperless-maverick-service
            port:
              number: 80
  - host: app.mataresit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paperless-maverick-service
            port:
              number: 80
  - host: api.mataresit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paperless-maverick-service
            port:
              number: 80
