
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase';

// Use environment variables for local development, fallback to production values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://mpmkbtsufihzdelrlszs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage adapter that respects "Remember Me" preference
// When session-only mode is active, auth tokens go to sessionStorage (cleared on browser close)
// Otherwise, tokens persist in localStorage (default Supabase behavior)
const SESSION_ONLY_KEY = 'mataresit-session-only';

const createAuthStorage = (): Storage => {
  const isSessionOnly = (): boolean => {
    try {
      return sessionStorage.getItem(SESSION_ONLY_KEY) === 'true';
    } catch {
      return false;
    }
  };

  return {
    getItem: (key: string): string | null => {
      try {
        // Check sessionStorage first (for session-only tokens), then localStorage
        return sessionStorage.getItem(key) ?? localStorage.getItem(key);
      } catch {
        return null;
      }
    },
    setItem: (key: string, value: string): void => {
      try {
        if (isSessionOnly()) {
          sessionStorage.setItem(key, value);
          localStorage.removeItem(key);
        } else {
          localStorage.setItem(key, value);
          sessionStorage.removeItem(key);
        }
      } catch {
        // Storage quota exceeded or unavailable
      }
    },
    removeItem: (key: string): void => {
      try {
        localStorage.removeItem(key);
        sessionStorage.removeItem(key);
      } catch {
        // Ignore
      }
    },
    get length(): number {
      try {
        return localStorage.length;
      } catch {
        return 0;
      }
    },
    key(index: number): string | null {
      try {
        return localStorage.key(index);
      } catch {
        return null;
      }
    },
    clear(): void {
      try {
        localStorage.clear();
        sessionStorage.clear();
      } catch {
        // Ignore
      }
    },
  };
};

// Create Supabase client with optimized real-time configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
    // Heartbeat interval to keep connection alive (configurable, default: 30 seconds)
    heartbeatIntervalMs: parseInt(import.meta.env.VITE_REALTIME_HEARTBEAT_INTERVAL || '30000', 10),
    // Reconnect timeout settings with exponential backoff
    reconnectAfterMs: (tries: number) => Math.min(1000 * Math.pow(2, tries), 30000),
    // Logger for debugging - use proper logger function format
    logger: (import.meta.env.DEV || import.meta.env.VITE_REALTIME_DEBUG === 'true')
      ? (kind: string, msg: string, data?: any) => {
          console.log(`[Supabase Realtime ${kind}]`, msg, data || '');
        }
      : undefined,
  },
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    // Storage key for auth state
    storageKey: 'mataresit-auth',
    // Custom storage adapter for "Remember Me" support
    storage: createAuthStorage(),
  },
  // Global configuration
  global: {
    headers: {
      'X-Client-Info': 'mataresit-web',
    },
  },
});

// Initialize real-time connection when client is created
// This helps ensure the connection is established early
if (typeof window !== 'undefined') {
  // Only in browser environment

  // Connect to real-time service
  // Note: Connection status will be logged through individual channel subscriptions
  supabase.realtime.connect();

  if (import.meta.env.DEV) {
    console.log('🔄 Supabase real-time client initialized (v2)');
  }
}
